import json
import os
import sqlite3
import unittest
from unittest.mock import patch
from pathlib import Path, PureWindowsPath
from tempfile import TemporaryDirectory

from multinexus.adapters import zcode_native_rules as rules


from contextlib import contextmanager

@contextmanager
def connect(path):
    db=sqlite3.connect(path)
    try:
        with db: yield db
    finally: db.close()


def native_database(path):
    with connect(path) as db:
        db.execute('PRAGMA journal_mode=WAL')
        db.execute('CREATE TABLE session(id TEXT PRIMARY KEY,project_id TEXT NOT NULL,workspace_id TEXT,path TEXT,directory TEXT NOT NULL)')
        db.execute('CREATE TABLE permission(project_id TEXT PRIMARY KEY,time_created INTEGER NOT NULL,time_updated INTEGER NOT NULL,data TEXT NOT NULL)')
        db.execute('CREATE TABLE local_setting(scope TEXT NOT NULL,scope_id TEXT NOT NULL,namespace TEXT NOT NULL,key TEXT NOT NULL,value TEXT NOT NULL,schema_version INTEGER NOT NULL,time_created INTEGER NOT NULL,time_updated INTEGER NOT NULL,PRIMARY KEY(scope,scope_id,namespace,key))')


class RestrictionTests(unittest.TestCase):
    def setUp(self):
        self.tmp=TemporaryDirectory();self.addCleanup(self.tmp.cleanup)
        self.root=Path(self.tmp.name).resolve();self.root.chmod(0o700)
        self.path=self.root/'session.sqlite';native_database(self.path)
        self.work=self.root/'workspace';self.work.mkdir();self.sid='sess_test';self.project=rules.native_project_id(self.work)

    def initialize(self):
        return rules.initialize_bash_restriction(self.path,self.work,self.sid)

    def verify(self, **kwargs):
        return rules.verify_bash_restriction(self.path,self.work,self.sid,**kwargs)

    def insert_session(self, *, sid=None, project=None, path=None):
        with connect(self.path) as db:db.execute('INSERT INTO session VALUES(?,?,?,?,?)',(sid or self.sid,project or self.project,None,path or str(self.work),str(self.work)))

    def setting(self, value, *, key='ruleset', scope='project', project=None, version=1):
        with connect(self.path) as db:db.execute('INSERT OR REPLACE INTO local_setting VALUES(?,?,?,?,?,?,1,1)',(scope,project or self.project,'permission',key,value,version))

    def test_first_input_bootstrap_then_persisted_session_and_cold_verify(self):
        first=self.initialize();self.assertFalse(first['session_persisted'])
        self.assertEqual(first['rule_sha256'],rules.RULE_SHA256)
        self.assertEqual(self.verify(bootstrap=True),first)
        with self.assertRaises(rules.ZCodeNativeRuleError):self.verify()
        self.insert_session();self.setting('{"mode":"build"}',key='mode')
        self.assertTrue(self.verify()['session_persisted'])
        with connect(self.path) as db:
            self.assertEqual(db.execute("SELECT value FROM local_setting WHERE key='ruleset'").fetchone()[0],rules.RULESET)

    def test_project_id_matches_audited_ascii_slugging_and_truncation(self):
        self.assertEqual(rules.native_project_id(Path('/Foo A/中文/.Test')), 'proj_foo-a-.test')
        self.assertEqual(rules.native_project_id(Path('/'+'a'*90)), 'proj_'+'a'*80)
        self.assertEqual(rules.native_project_id(Path('/')), 'proj_session')

    def test_project_id_matches_observed_native_mac_and_windows_rows(self):
        # Captured from SHA-pinned native fixtures, not generated by this helper.
        self.assertEqual(rules.native_project_id(Path('/private/tmp/zcode.native-oracle.v1-ucmak1n0/workspace')), 'proj_private-tmp-zcode.native-oracle.v1-ucmak1n0-workspace')
        self.assertEqual(rules.native_project_id(PureWindowsPath('C:\\ProgramData\\MultiNexus\\zcode-mock-20260906-nu_s3z1l\\workspace')), 'proj_c-programdata-multinexus-zcode-mock-20260906-nu_s3z1l-workspace')

    def test_wrong_session_project_or_workspace_cannot_resume(self):
        self.initialize()
        for kwargs in ({'sid':'sess_other'},{'project':'foreign'},{'path':'/foreign'}):
            with self.subTest(kwargs=kwargs):
                with connect(self.path) as db: db.execute('DELETE FROM session')
                self.insert_session(**kwargs)
                with self.assertRaises(rules.ZCodeNativeRuleError): self.verify()
                with connect(self.path) as db:
                    self.assertEqual(db.execute("SELECT value FROM local_setting WHERE key='ruleset'").fetchone()[0], rules.RULESET)

    def test_fresh_init_rejects_persisted_session_before_policy_write(self):
        self.insert_session()
        with self.assertRaises(rules.ZCodeNativeRuleError): self.initialize()
        with connect(self.path) as db:
            self.assertEqual(db.execute('SELECT count(*) FROM local_setting').fetchone()[0], 0)

    def test_injected_failure_after_insert_rolls_back_transaction(self):
        original_connect = sqlite3.connect
        class FailingInsert(sqlite3.Connection):
            def execute(self, sql, *args):
                result = super().execute(sql, *args)
                if sql.startswith('INSERT INTO local_setting'):
                    raise sqlite3.OperationalError('injected after insert')
                return result
        def faulty_connection(*args, **kwargs):
            return original_connect(*args, factory=FailingInsert, **kwargs)
        with patch.object(rules.sqlite3, 'connect', side_effect=faulty_connection):
            with self.assertRaises(sqlite3.OperationalError): self.initialize()
        with connect(self.path) as db:
            self.assertEqual(db.execute('SELECT count(*) FROM local_setting').fetchone()[0], 0)

    def test_foreign_legacy_and_existing_rules_are_never_overwritten(self):
        with connect(self.path) as db:db.execute('INSERT INTO permission VALUES(?,1,1,?)',(self.project,'{"allow":[{"toolName":"Bash"}]}'))
        with self.assertRaises(rules.ZCodeNativeRuleError):self.initialize()
        with connect(self.path) as db:db.execute('DELETE FROM permission')
        self.setting('{"version":1}')
        with self.assertRaises(rules.ZCodeNativeRuleError):self.initialize()
        with connect(self.path) as db:self.assertEqual(db.execute('SELECT value FROM local_setting').fetchone()[0],'{"version":1}')

    def test_missing_or_changed_rule_cannot_be_repaired_on_resume(self):
        self.insert_session()
        with self.assertRaises(rules.ZCodeNativeRuleError):self.verify()
        for value in ('{}','null','{"ask":[{"toolName":"Bash"}],"version":true}',
                      '{"ask":[{"toolName":"Bash"}],"version":1,"allow":[]}',
                      '{"ask":[{"toolName":"Bash","ruleContent":"echo *"}],"version":1}',
                      '{"ask":[],"ask":[{"toolName":"Bash"}],"version":1}',
                      '{"ask":[{"toolName":"Bash"}],"version":NaN}'):
            with self.subTest(value=value):
                self.setting(value)
                with self.assertRaises(rules.ZCodeNativeRuleError):self.verify()
        self.setting(json.dumps(json.loads(rules.RULESET),indent=2));self.verify()

    def test_permission_namespace_is_closed_except_observed_build_mode(self):
        self.initialize();self.insert_session()
        for kwargs in ({'key':'unknown'}, {'scope':'user'}, {'project':'another'}, {'version':2}):
            with self.subTest(kwargs=kwargs):
                with connect(self.path) as db:db.execute("DELETE FROM local_setting WHERE key!='ruleset'")
                self.setting('{"mode":"build"}',key='mode',**{k:v for k,v in kwargs.items() if k!='key'}) if 'key' not in kwargs else self.setting('{}',**kwargs)
                with self.assertRaises(rules.ZCodeNativeRuleError):self.verify()
        with connect(self.path) as db:db.execute("DELETE FROM local_setting WHERE key!='ruleset'")
        self.setting('{"mode":"yolo"}',key='mode')
        with self.assertRaises(rules.ZCodeNativeRuleError):self.verify()

    def test_missing_database_not_created_and_unsafe_file_links_rejected(self):
        absent=self.root/'missing'/'session.sqlite'
        with self.assertRaises(OSError):rules.initialize_bash_restriction(absent,self.work,self.sid)
        self.assertFalse(absent.exists())
        link=self.root/'db-hardlink';os.link(self.path,link)
        with self.assertRaises(rules.ZCodeNativeRuleError):self.initialize()
        link.unlink()

    def test_unknown_schema_or_sql_trigger_cannot_mutate_state(self):
        with connect(self.path) as db:db.execute('CREATE TRIGGER surprise AFTER INSERT ON local_setting BEGIN DELETE FROM session; END')
        with self.assertRaises(rules.ZCodeNativeRuleError):self.initialize()
        with connect(self.path) as db:
            self.assertEqual(db.execute('SELECT count(*) FROM local_setting').fetchone()[0],0)
            db.execute('DROP TRIGGER surprise');db.execute('ALTER TABLE local_setting ADD COLUMN extra TEXT')
        with self.assertRaises(rules.ZCodeNativeRuleError):self.initialize()

    def test_sql_lock_fails_without_grant_or_partial_rule(self):
        db=sqlite3.connect(self.path);self.addCleanup(db.close);db.execute('BEGIN IMMEDIATE')
        with self.assertRaises(sqlite3.OperationalError):self.initialize()
        db.rollback();self.assertEqual(db.execute('SELECT count(*) FROM local_setting').fetchone()[0],0)


if __name__=='__main__':unittest.main()
