"""Standalone + Discord + single-agent setup wizard.

Run ``python -m multinexus.setup`` for fresh setup or add ``--check`` to
validate local configuration without contacting Discord or an agent provider.
"""

from __future__ import annotations

import argparse
import getpass
import json
import os
import re
import shutil
import sys
import tempfile
import tomllib
from collections.abc import Callable
from pathlib import Path
from typing import TextIO


CHECK_OK = 0
CHECK_INVALID = 2

EXECUTORS = {
    "claude": ("claude_bin", "claude"),
    "codex": ("codex_bin", "codex.cmd" if os.name == "nt" else "codex"),
    "opencode": ("opencode_bin", "opencode"),
    "omp": ("omp_bin", "omp"),
    "hermes": ("hermes_bin", "hermes"),
}
EXECUTOR_CHOICES = {
    "1": "claude",
    "2": "codex",
    "3": "opencode",
    "4": "omp",
    "5": "hermes",
    **{name: name for name in EXECUTORS},
}
# Check-only adapters: verifiable by --check but intentionally NOT creatable by
# the interactive wizard (EXECUTOR_CHOICES stays at five entries).
CHECK_EXECUTORS = {
    "qoder": ("qoder_bin", "qodercli"),
    "grok": ("grok_bin", "grok"),
    "acp": ("acp_command", ""),
}
AGENT_ID_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_-]*$")
ENV_KEY_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _print(message: str = "", *, out: TextIO) -> None:
    print(message, file=out)


def _ask(
    prompt: str,
    *,
    input_fn: Callable[[str], str],
    out: TextIO,
    validate: Callable[[str], str | None],
) -> str:
    while True:
        value = input_fn(prompt).strip()
        error = validate(value)
        if error is None:
            return value
        _print(f"  输入无效：{error}", out=out)


def _validate_agent_id(value: str) -> str | None:
    if not value or not AGENT_ID_RE.fullmatch(value):
        return "agent id 格式无效；仅可使用字母、数字、_ 和 -，且必须以字母或数字开头。"
    return None


def _validate_nonempty(value: str) -> str | None:
    return None if value else "不能为空。"


def _validate_executor(value: str) -> str | None:
    return None if value.lower() in EXECUTOR_CHOICES else "请选择 1-5 或输入受支持的 executor 名称。"


def _validate_work_dir(value: str) -> str | None:
    path = Path(value).expanduser()
    if not path.is_absolute():
        return "work dir 必须是绝对路径。"
    if not path.is_dir():
        return "work dir 目录不存在。"
    return None


def _validate_snowflake(value: str) -> str | None:
    return None if value.isdigit() else "Discord ID 必须是纯数字。"


def _token_env_name(agent_id: str) -> str:
    normalized = re.sub(r"[^A-Za-z0-9]+", "_", agent_id).strip("_").upper()
    return f"DISCORD_{normalized}_TOKEN"


def _toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _render_config(
    *,
    agent_id: str,
    display_name: str,
    executor: str,
    work_dir: Path,
    channel_id: int,
    user_id: int,
    token_env: str,
) -> str:
    binary_field, binary = EXECUTORS[executor]
    return (
        "# Generated by: python -m multinexus.setup\n"
        "# Standalone profile: Discord bridge calls one local executor directly.\n\n"
        "[defaults]\n"
        "agentd_mode = false\n\n"
        "[[agents]]\n"
        f"id = {_toml_string(agent_id)}\n"
        f"adapter = {_toml_string(executor)}\n"
        f"display_name = {_toml_string(display_name)}\n"
        f"token_env = {_toml_string(token_env)}\n"
        f"work_dir = {_toml_string(str(work_dir))}\n"
        f"{binary_field} = {_toml_string(binary)}\n"
        f"channels = [{channel_id}]\n"
        f"allowed_user_ids = [{user_id}]\n"
    )


def _atomic_write_text(path: Path, content: str, *, mode: int | None = None) -> None:
    """Replace *path* atomically using a temporary file in the same directory."""
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temp_name = tempfile.mkstemp(
        prefix=f"{path.name}.", suffix=".tmp", dir=path.parent
    )
    temp_path = Path(temp_name)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        if mode is not None:
            os.chmod(temp_path, mode)
        os.replace(temp_path, path)
    except BaseException:
        temp_path.unlink(missing_ok=True)
        raise


def _upsert_env(existing: str, key: str, value: str) -> str:
    if not ENV_KEY_RE.fullmatch(key):
        raise ValueError("invalid environment variable name")
    replacement = f"{key}={value}"
    pattern = re.compile(rf"^\s*(?:export\s+)?{re.escape(key)}\s*=")
    lines = existing.splitlines()
    output: list[str] = []
    replaced = False
    for line in lines:
        if pattern.match(line):
            if not replaced:
                output.append(replacement)
                replaced = True
            continue
        output.append(line)
    if not replaced:
        output.append(replacement)
    return "\n".join(output) + "\n"


def _read_env_values(path: Path) -> dict[str, str]:
    """Read simple dotenv assignments without exporting or printing values."""
    if not path.is_file():
        return {}
    values: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[7:].lstrip()
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()
        if not ENV_KEY_RE.fullmatch(key):
            continue
        if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
            value = value[1:-1]
        values[key] = value
    return values


def _merged_agent(defaults: object, agent: object) -> dict:
    if not isinstance(defaults, dict) or not isinstance(agent, dict):
        return {}
    return {**defaults, **agent}


def check_configuration(root: Path | str, *, out: TextIO = sys.stdout) -> int:
    """Sanitize-check local config without network or provider calls."""
    root = Path(root).expanduser().resolve()
    config_path = root / "agents.toml"
    env_path = root / ".env"
    errors = 0
    warnings = 0

    if not config_path.is_file():
        _print("ERROR agents.toml 不存在。", out=out)
        _print("CHECK_FAILED errors=1 warnings=0", out=out)
        return CHECK_INVALID

    try:
        data = tomllib.loads(config_path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, tomllib.TOMLDecodeError):
        _print("ERROR agents.toml TOML 无效或不可读。", out=out)
        _print("CHECK_FAILED errors=1 warnings=0", out=out)
        return CHECK_INVALID

    defaults = data.get("defaults", {}) if isinstance(data, dict) else {}
    agents = data.get("agents", []) if isinstance(data, dict) else []
    if not isinstance(agents, list) or not agents:
        _print("ERROR agents.toml 没有 [[agents]] 条目。", out=out)
        _print("CHECK_FAILED errors=1 warnings=0", out=out)
        return CHECK_INVALID

    _print(f"OK agents.toml: parsed ({len(agents)} agent)", out=out)
    env_values = _read_env_values(env_path)
    if env_path.exists() and os.name != "nt":
        if env_path.stat().st_mode & 0o077:
            errors += 1
            _print("ERROR .env 权限过宽；请执行 chmod 600 .env。", out=out)
        else:
            _print("OK .env mode: owner-only", out=out)
    elif not env_path.exists():
        warnings += 1
        _print("WARNING .env 不存在；仅检查当前 process environment。", out=out)

    for index, agent in enumerate(agents, start=1):
        merged = _merged_agent(defaults, agent)
        agent_id = str(merged.get("id", "")).strip()
        label = agent_id or f"#{index}"
        if not agent_id:
            errors += 1
            _print(f"ERROR agent {label}: id missing", out=out)

        token_env = str(merged.get("token_env", "")).strip()
        token_present = bool(token_env and (os.environ.get(token_env) or env_values.get(token_env)))
        if not token_env:
            errors += 1
            _print(f"ERROR agent {label} token_env: missing", out=out)
        elif not token_present:
            errors += 1
            _print(f"ERROR agent {label} token: missing ({token_env})", out=out)
        else:
            _print(f"OK agent {label} token: present ({token_env})", out=out)

        work_dir_value = str(merged.get("work_dir", "")).strip()
        work_dir = Path(work_dir_value).expanduser() if work_dir_value else None
        if work_dir is None or not work_dir.is_absolute() or not work_dir.is_dir():
            errors += 1
            _print(f"ERROR agent {label} work_dir: missing or invalid", out=out)
        else:
            _print(f"OK agent {label} work_dir: exists", out=out)

        executor = str(merged.get("adapter", "")).strip().lower()
        executor_spec = EXECUTORS.get(executor) or CHECK_EXECUTORS.get(executor)
        if executor_spec is None:
            errors += 1
            _print(f"ERROR agent {label} executor: unsupported ({executor or 'missing'})", out=out)
        else:
            binary_field, default_binary = executor_spec
            binary = str(merged.get(binary_field, default_binary)).strip()
            resolved = shutil.which(binary) if binary else None
            if resolved is None:
                errors += 1
                _print(f"ERROR agent {label} executor: missing ({binary or executor})", out=out)
            else:
                _print(f"OK agent {label} executor: available ({executor})", out=out)

        if not merged.get("channels"):
            warnings += 1
            _print(f"WARNING channels 未限制（agent {label}）。", out=out)
        if not merged.get("allowed_user_ids"):
            warnings += 1
            _print(f"WARNING allowed_user_ids 未限制（agent {label}）。", out=out)

    if errors:
        _print(f"CHECK_FAILED errors={errors} warnings={warnings}", out=out)
        return CHECK_INVALID
    _print(f"CHECK_OK errors=0 warnings={warnings}", out=out)
    return CHECK_OK


def _show_discord_checklist(*, out: TextIO) -> None:
    _print("MultiNexus Standalone 首次配置", out=out)
    _print("", out=out)
    _print("请先在 Discord Developer Portal 完成：", out=out)
    _print("  1. https://discord.com/developers/applications", out=out)
    _print("  2. 创建 Application 与 Bot，并启用 Message Content Intent", out=out)
    _print("  3. 用 bot + applications.commands scopes 邀请 Bot", out=out)
    _print("  4. 开启 Discord Developer Mode，复制 channel ID 与你的 user ID", out=out)
    _print("Bot token 将通过隐藏输入读取；本工具不会调用 Discord API。", out=out)
    _print("", out=out)


def run_setup(
    root: Path | str,
    *,
    input_fn: Callable[[str], str] = input,
    secret_fn: Callable[[str], str] = getpass.getpass,
    out: TextIO = sys.stdout,
) -> int:
    root = Path(root).expanduser().resolve()
    config_path = root / "agents.toml"
    env_path = root / ".env"

    if config_path.exists():
        _print("检测到现有 agents.toml；不会覆盖。下面只执行 sanitized check。", out=out)
        code = check_configuration(root, out=out)
        _print("如需重新配置，请先自行备份并移走 agents.toml。", out=out)
        return code

    _show_discord_checklist(out=out)
    agent_id = _ask(
        "Agent ID（如 mac-claude）：",
        input_fn=input_fn,
        out=out,
        validate=_validate_agent_id,
    )
    display_name = _ask(
        "显示名称：", input_fn=input_fn, out=out, validate=_validate_nonempty
    )
    executor_answer = _ask(
        "Executor [1=claude, 2=codex, 3=opencode, 4=omp, 5=hermes]：",
        input_fn=input_fn,
        out=out,
        validate=_validate_executor,
    ).lower()
    executor = EXECUTOR_CHOICES[executor_answer]
    work_dir_answer = _ask(
        "绝对 work dir：",
        input_fn=input_fn,
        out=out,
        validate=_validate_work_dir,
    )
    work_dir = Path(work_dir_answer).expanduser().resolve()
    channel_id = int(
        _ask(
            "Authorized Discord channel ID：",
            input_fn=input_fn,
            out=out,
            validate=_validate_snowflake,
        )
    )
    user_id = int(
        _ask(
            "你的 Discord user ID：",
            input_fn=input_fn,
            out=out,
            validate=_validate_snowflake,
        )
    )

    _binary_field, binary = EXECUTORS[executor]
    if shutil.which(binary) is None:
        _print(f"ERROR 未找到 executor：{binary}。请先安装并确认它在 PATH 中，再重试。", out=out)
        return CHECK_INVALID

    token = secret_fn("Discord Bot Token（隐藏输入）：").strip()
    if not token or any(character.isspace() or character == "\x00" for character in token):
        _print("ERROR token 为空或包含空白/控制字符；未写入任何配置。", out=out)
        return CHECK_INVALID

    token_env = _token_env_name(agent_id)
    config_text = _render_config(
        agent_id=agent_id,
        display_name=display_name,
        executor=executor,
        work_dir=work_dir,
        channel_id=channel_id,
        user_id=user_id,
        token_env=token_env,
    )
    existing_env = env_path.read_text(encoding="utf-8") if env_path.exists() else ""
    env_text = _upsert_env(existing_env, token_env, token)

    _atomic_write_text(env_path, env_text, mode=0o600)
    _atomic_write_text(config_path, config_text)
    _print("配置已写入：agents.toml 与 .env（token: present）。", out=out)
    code = check_configuration(root, out=out)
    if code == CHECK_OK:
        _print("启动命令：python multinexus.py --platform discord --config agents.toml", out=out)
    return code


def _parse_args(argv: list[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="python -m multinexus.setup",
        description="配置或检查 Standalone + Discord + 单 agent MultiNexus。",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="只读检查当前目录的 agents.toml/.env，不调用 Discord 或 provider。",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    try:
        if args.check:
            return check_configuration(Path.cwd())
        return run_setup(Path.cwd())
    except (EOFError, KeyboardInterrupt):
        _print("\n配置已取消；未完成的输入不会保存。", out=sys.stderr)
        return 130


if __name__ == "__main__":
    raise SystemExit(main())
